# DeepTraffic
LANES_SIDE = 3
PATCHES_AHEAD = 30
PATCHES_BEHIND = 10
HISTORY = 1
OBS = 'conv'

# BasicConditionChecker
SWITCH_LANE_SAFETY_FRONT = 4

# Runner
PLAY_EPISODE_STEPS = 200
PLAY_EPISODE_SLEEP_TIME = 0.5
