# DeepTraffic
LANES_SIDE = 3
PATCHES_AHEAD = 30
PATCHES_BEHIND = 10
HISTORY = 1
OBS = 'conv'
SPEED_FACTOR = 2000  # SPEED_FACTOR * state_value = real_speed


# ConditionChecker
SAFETY_FRONT = 4
SWITCH_LANE_SAFETY_FRONT = 5


# BehaviorTree
ACT_NOACTION = "noAction"
ACT_ACCELERATE = "accelerate"
ACT_DECELERATE = "decelerate"
ACT_SWITCHLEFT = "goLeft"
ACT_SWITCHRIGHT = "goRight"
ACT_LEARN = "learnAction"


# Agent
ACT_TO_ACTIDX = {
    ACT_NOACTION: 0,
    ACT_ACCELERATE: 1,
    ACT_DECELERATE: 2,
    ACT_SWITCHLEFT: 3,
    ACT_SWITCHRIGHT: 4
}


# Runner
PLAY_EPISODE_STEPS = 200
PLAY_EPISODE_SLEEP_TIME = 0.25
CHANGE_ACT_SLEEP_TIME = 2.0
